sudo: required
services:
  - docker

before_install:
  - docker build -t josemelendezbolanos21/docker-example -f Dockerfile.dev .

script:
  - docker run josemelendezbolanos21/docker-example npm run test -- --coverage
  
