sudo: required
services:
  - docker

before_install:
  - docker build -t josemelendezbolanos21/docker-example -f Dockerfile.dev .

script:
  - docker run josemelendezbolanos21/docker-example npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-example"
  env: "DockerExample-env"
  bucket_name: "elasticbeanstalk-us-east-2-501000292805"
  bucket_path: "docker-example"
  on:
    branch: master

  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"

